# Generated by Django 3.2.3 on 2021-06-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refshelf', '0006_authors_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(max_length=100, verbose_name='Переплет')),
            ],
            options={
                'verbose_name': 'Переплет',
            },
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250, verbose_name='Название книги')),
                ('cover_picture', models.ImageField(upload_to='book//%Y/%m/%d/', verbose_name='Фото обложки')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость книги, BYN')),
                ('book_year', models.PositiveSmallIntegerField(verbose_name='Год издания')),
                ('book_pages', models.PositiveSmallIntegerField(verbose_name='Количество страниц')),
                ('book_icbn', models.PositiveIntegerField(verbose_name='Номер ISBN')),
                ('book_weight', models.PositiveSmallIntegerField(verbose_name='Вес книги')),
                ('book_format', models.CharField(choices=[('Сверхкрупный', 'Сверхкрупный'), ('Крупный', 'Крупный'), ('Средний', 'Средний'), ('Малый', 'Малый'), ('Сверхмалый', 'Сверхмалый')], default='Средний', max_length=25, verbose_name='Формат книги')),
                ('book_quantity', models.PositiveIntegerField(verbose_name='Количество книг на складе')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('age_restrictions', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='0+', max_length=3, verbose_name='Возрастные ограничения')),
                ('book_rating', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], verbose_name='Рейтинг')),
                ('book_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания в каталоге')),
                ('book_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('book_authors', models.ManyToManyField(related_name='books', to='refshelf.Authors')),
                ('book_bindings', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='books.binding')),
                ('book_genres', models.ManyToManyField(related_name='books', to='refshelf.Genre')),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='refshelf.publisher')),
                ('book_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='refshelf.bookseries')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
