# Generated by Django 3.2.3 on 2021-06-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refshelf', '0006_authors_picture'),
        ('books', '0002_agerestr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binding',
            options={'verbose_name': 'Переплет', 'verbose_name_plural': 'Переплеты'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_authors',
            field=models.ManyToManyField(related_name='books', to='refshelf.Authors', verbose_name='Автор(ы)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_bindings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='books.binding', verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genres',
            field=models.ManyToManyField(related_name='books', to='refshelf.Genre', verbose_name='Жанр(ы)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_icbn',
            field=models.CharField(max_length=200, verbose_name='Номер ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='refshelf.publisher', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='refshelf.bookseries', verbose_name='Серия книг'),
        ),
    ]
