# Generated by Django 3.2.3 on 2021-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210610_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Рейтинг'),
        ),
    ]
