# Generated by Django 3.2.3 on 2021-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Рекомендуемый товар'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='book//%Y/%m/%d/', verbose_name='Фото обложки'),
        ),
    ]
