# Generated by Django 3.2.3 on 2021-06-29 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Товары в козине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 29, 13, 49, 52, 155076, tzinfo=utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Модифицировано'),
        ),
    ]
