# Generated by Django 3.2.3 on 2021-06-29 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20210629_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='ct_item_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 29, 13, 52, 38, 122008, tzinfo=utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='ct_item_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Модифицировано'),
        ),
    ]
