# Generated by Django 3.2.3 on 2021-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_index',
            field=models.IntegerField(default='220000', verbose_name='Индекс'),
        ),
    ]
