# Generated by Django 3.2.3 on 2021-06-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210618_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='details',
            new_name='user_details',
        ),
    ]
