# Generated by Django 3.2.3 on 2021-06-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='sale_staff',
        ),
    ]
