# Generated by Django 3.2.3 on 2021-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20, verbose_name='Название жанра')),
            ],
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
