# Generated by Django 3.2.3 on 2021-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refshelf', '0002_auto_20210523_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание жанра'),
        ),
    ]
