# Generated by Django 3.2.3 on 2021-05-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refshelf', '0004_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100, verbose_name='Серия')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name='Описание серии')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
