# Generated by Django 3.2.3 on 2021-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refshelf', '0005_bookseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='picture',
            field=models.ImageField(default='img', upload_to='authors//%Y/%m/%d/', verbose_name='Фото автора'),
            preserve_default=False,
        ),
    ]
