# Generated by Django 3.2.3 on 2021-07-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0006_auto_20210629_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.TextField(verbose_name='Контактный номер')),
                ('order_status', models.CharField(choices=[('Новый', 'Новый'), ('В обработке', 'В обработке'), ('Неудавшийся', 'Неудавшийся'), ('Исполненный', 'Исполненный')], default='Новый', max_length=11, verbose_name='Статус заказа')),
                ('order_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order_modified', models.DateTimeField(auto_now=True, verbose_name='Модифицирован')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.cart', verbose_name='Заказ')),
            ],
        ),
    ]
