# Generated by Django 3.2.3 on 2021-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_import', models.FileField(upload_to='csv-data')),
                ('file_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
