# Generated by Django 3.2.3 on 2021-06-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvimport',
            options={'verbose_name': 'Файл импорта книг', 'verbose_name_plural': 'Файлы импорта книг'},
        ),
        migrations.AlterField(
            model_name='csvimport',
            name='file_import',
            field=models.FileField(upload_to='csv-data', verbose_name='CSV файл'),
        ),
    ]
